Adding dbus-launch in test container PATH
redhat-developer/kam pull request #103
Opened 2020-12-02 07:24 UTC by amitkrout

**What type of PR is this?**
/kind failing-test
/kind enhancement

**What does this PR do / why we need it**:
This fix will issue coming from another pr - https://github.com/redhat-developer/kam/pull/87

Issue log - https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/redhat-developer_kam/87/pull-ci-redhat-developer-kam-master-v4.5-integration-e2e/1333827600312700928#1:build-log.txt%3A943

**Have you updated the necessary documentation?**

* [ ] Documentation update is required by this PR.
* [ ] Documentation has been updated.

**Which issue(s) this PR fixes**:

Fixes ```Command stderr:  ✗  unable to use access-token from keyring/env-var: exec: "dbus-launch": executable file not found in $PATH, please pass a valid token to --git-host-access-token```

**How to test changes / Special notes to the reviewer**:
Pr https://github.com/redhat-developer/kam/pull/87 should not throw ```dbus-launch``` error

2020-12-02 08:09 UTC, bigkevmcd requested changes
This is not the solution to this.

We should not require dbus or a keyring (this is imposing a large burden on folks who want to run it in a container).

2020-12-02 08:22 UTC, amitkrout commented
We need a proper fix in code level not in the test container cc_ @bigkevmcd 
/hold

2020-12-03 11:13 UTC, amitkrout commented
/retest

2020-12-03 14:54 UTC, amitkrout commented
/retest

2020-12-04 08:12 UTC, amitkrout commented on scripts/openshiftci-presubmit-all-tests.sh
>  kam version
```
Login to the cluster as a developer user
+ git log -n 5
commit dc909af9e8d2bd4474a5dbecf4ad1517fb76d985
Merge: 337dae1 d7f8e42
Author: ci-robot <ci-robot@openshift.io>
Date:   Tue Dec 1 07:00:14 2020 +0000

    Merge commit 'd7f8e426a16b16a3aa3f34b5d54b067809a5e027'
```

The latest branch commit SHA is ```dc909af9e8d2bd4474a5dbecf4ad1517fb76d985```
```
+ kam version
kam version v0.0.14-15-gdc909af
```
@bigkevmcd 
Seems kam version capturing the correct SHA that is ```commit dc909af9e8d2bd4474a5dbecf4ad1517fb76d985```. However I am not sure why the latest commit has two SHA that is  ```Merge commit 'd7f8e426a16b16a3aa3f34b5d54b067809a5e027'``` and ```Merge commit 'd7f8e426a16b16a3aa3f34b5d54b067809a5e027'``` ?

2020-12-04 12:43 UTC, amitkrout commented
Lets not bandage things, so i am closing it. Probably i need to investigate around token things.
/close

2020-12-04 12:43 UTC, closed without merging