Create an application/service in the new environment and push configu…
redhat-developer/kam pull request #265
Opened 2021-08-05 10:40 UTC by varshab1210

…ration to GitOps repository scenarios

**What type of PR is this?**

/kind enhancement

**What does this PR do / why we need it**:

https://github.com/redhat-developer/kam/issues/136

**Have you updated the necessary documentation?**

* [ ] Documentation update is required by this PR.
* [ ] Documentation has been updated.

**Which issue(s) this PR fixes**:

Fixes #?

https://github.com/redhat-developer/kam/issues/136

**How to test changes / Special notes to the reviewer**:

2021-08-06 06:54 UTC, amitkrout requested changes

2021-08-06 06:54 UTC, amitkrout commented on test/e2e/features/basic.feature
> +    Scenario: Commit and Push configuration to GitOps repoository
This scenario is not required. Please remove it

2021-08-06 10:55 UTC, varshab1210 commented
/retest

2021-08-09 05:39 UTC, varshab1210 commented
/retest

2021-08-10 07:54 UTC, varshab1210 commented
I tested the pr locally and it went fine. I am not sure why its failing in CI. Can you please take a look @amitkrout 

```
$ make e2e
Log successfully started, logging into: /home/varshab/go/src/github.com/redhat-developer/kam/test/e2e/out/test-results/e2e_2021-8-10_13-13-39.log
Running e2e test in: /home/varshab/go/src/github.com/redhat-developer/kam/test/e2e/out/test-run
Working directory set to: /home/varshab/go/src/github.com/redhat-developer/kam/test/e2e/out/test-run
Before suite
The bash instance has been started and will be used for testing.
Before feature
Feature: Basic test
  Checks whether KAM top-level commands behave correctly.
Before scenario

  Scenario: KAM version                                    # features/basic.feature:5
    When executing "kam version" succeeds                  # shell.go:230 -> github.com/code-ready/clicumber/testsuite.ExecuteCommandSucceedsOrFails
    Then stderr should be empty                            # shell.go:302 -> github.com/code-ready/clicumber/testsuite.CommandReturnShouldBeEmpty
    And stdout should match "kam\sversion\sv\d+\.\d+\.\d+" # shell.go:326 -> github.com/code-ready/clicumber/testsuite.CommandReturnShouldMatch
After scenario
2021/08/10 13:13:39 unable to delete repository: Not Found
Before scenario

  Scenario: Execute KAM bootstrap command without --push-to-git=true flag                                                                                                                                                                                 # features/basic.feature:10
    When executing "kam bootstrap --service-repo-url $SERVICE_REPO_URL --gitops-repo-url $GITOPS_REPO_URL --image-repo $IMAGE_REPO --dockercfgjson $DOCKERCONFIGJSON_PATH --git-host-access-token $GIT_ACCESS_TOKEN --output bootstrapresources" succeeds # shell.go:230 -> github.com/code-ready/clicumber/testsuite.ExecuteCommandSucceedsOrFails
    Then stderr should be empty                                                                                                                                                                                                                           # shell.go:302 -> github.com/code-ready/clicumber/testsuite.CommandReturnShouldBeEmpty
After scenario
2021/08/10 13:13:43 unable to delete repository: Not Found
Before scenario

  Scenario: Execute KAM bootstrap command that overwite the custom output manifest path                                                                                                                                                                               # features/basic.feature:14
    When executing "kam bootstrap --service-repo-url $SERVICE_REPO_URL --gitops-repo-url $GITOPS_REPO_URL --image-repo $IMAGE_REPO --dockercfgjson $DOCKERCONFIGJSON_PATH --git-host-access-token $GIT_ACCESS_TOKEN --output bootstrapresources --overwrite" succeeds # shell.go:230 -> github.com/code-ready/clicumber/testsuite.ExecuteCommandSucceedsOrFails
    Then stderr should be empty                                                                                                                                                                                                                                       # shell.go:302 -> github.com/code-ready/clicumber/testsuite.CommandReturnShouldBeEmpty
After scenario
2021/08/10 13:13:53 unable to delete repository: Not Found
Before scenario

  Scenario: KAM bootstrap command should fail if any one mandatory flag --git-host-access-token is missing       # features/basic.feature:18
    When executing "kam bootstrap --service-repo-url $SERVICE_REPO_URL --gitops-repo-url $GITOPS_REPO_URL" fails # shell.go:230 -> github.com/code-ready/clicumber/testsuite.ExecuteCommandSucceedsOrFails
    Then exitcode should not equal "0"                                                                           # shell.go:318 -> github.com/code-ready/clicumber/testsuite.CommandReturnShouldNotEqual
After scenario
2021/08/10 13:13:55 unable to delete repository: Not Found
Before scenario

  Scenario: Bringing the bootstrapped environment up                                                                                                                                                                                                                  # features/basic.feature:22
    Given gitops repository is created                                                                                                                                                                                                                                # kamsuite.go:163 -> /kamsuite.createRepository
    When executing "kam bootstrap --service-repo-url $SERVICE_REPO_URL --gitops-repo-url $GITOPS_REPO_URL --image-repo $IMAGE_REPO --dockercfgjson $DOCKERCONFIGJSON_PATH --git-host-access-token $GIT_ACCESS_TOKEN --output bootstrapresources --overwrite" succeeds # shell.go:230 -> github.com/code-ready/clicumber/testsuite.ExecuteCommandSucceedsOrFails
    Then executing "cd bootstrapresources" succeeds                                                                                                                                                                                                                   # shell.go:230 -> github.com/code-ready/clicumber/testsuite.ExecuteCommandSucceedsOrFails
    Then executing "git init ." succeeds                                                                                                                                                                                                                              # shell.go:230 -> github.com/code-ready/clicumber/testsuite.ExecuteCommandSucceedsOrFails
    Then executing "git add ." succeeds                                                                                                                                                                                                                               # shell.go:230 -> github.com/code-ready/clicumber/testsuite.ExecuteCommandSucceedsOrFails
    Then executing "git commit -m 'Initial commit.'" succeeds                                                                                                                                                                                                         # shell.go:230 -> github.com/code-ready/clicumber/testsuite.ExecuteCommandSucceedsOrFails
    Then executing "git remote add origin $GITOPS_REPO_URL" succeeds                                                                                                                                                                                                  # shell.go:230 -> github.com/code-ready/clicumber/testsuite.ExecuteCommandSucceedsOrFails
    Then executing "git branch -M main" succeeds                                                                                                                                                                                                                      # shell.go:230 -> github.com/code-ready/clicumber/testsuite.ExecuteCommandSucceedsOrFails
    Then executing "git push -u origin main" succeeds                                                                                                                                                                                                                 # shell.go:230 -> github.com/code-ready/clicumber/testsuite.ExecuteCommandSucceedsOrFails
    Then executing "cd .." succeeds                                                                                                                                                                                                                                   # shell.go:230 -> github.com/code-ready/clicumber/testsuite.ExecuteCommandSucceedsOrFails
After scenario
2021/08/10 13:14:09 Successfully deleted repository: "https://github.com/varshab1210/gitops.git"
Before scenario

  Scenario: Bringing the deployment infrastructure up      [...]

2021-08-10 09:16 UTC, varshab1210 commented
/retest

2021-08-10 10:28 UTC, amitkrout requested changes

2021-08-10 10:28 UTC, amitkrout commented on test/e2e/features/basic.feature
> +        When executing "kam service add --env-name new-env --app-name app-bus --service-name bus --git-repo-url $GIT_REPO_URL --pipelines-folder servicescenario" succeeds
Pass ```https://github.com/kam-bot/bus.git``` instead of $GIT_REPO_URL

2021-08-10 10:32 UTC, amitkrout requested changes
Looks like the CI cluster takes longer time to sync the application. Can you please increase timeout to 3mins, for example ```Wait for "180" seconds```. If it works then we can increase the CI resources and also we have to implement a proper wait logic.

2021-08-10 10:33 UTC, amitkrout requested changes

2021-08-11 05:47 UTC, amitkrout commented
/test v4.8-integration-e2e

2021-08-11 12:26 UTC, varshab1210 commented
I am able to reproduce the failure on 4.8 ocp cluster locally

2021-08-18 09:03 UTC, amitkrout commented
blocked due to - https://github.com/redhat-developer/kam/pull/266
/block

2021-08-20 09:45 UTC, varshab1210 commented
/retest

2021-08-24 11:36 UTC, amitkrout commented
/approve
/lgtm

2021-08-24 13:46 UTC, merged