Generated argocd application to use overlays folder instead of base
redhat-developer/kam pull request #93
Opened 2020-11-25 06:16 UTC by iam-veeramalla

**What type of PR is this?**
> /kind bug

**What does this PR do / why we need it**:
Generated argocd application to use overlays folder instead of base. Given that we have an overlays directory, which is for users to override the base, we should be using the overlays directory, otherwise nothing that is put into the overlays will be picked up.

**Have you updated the necessary documentation?**
NA 

**Which issue(s) this PR fixes**:
NA

**How to test changes / Special notes to the reviewer**:
Run `kam bootstrap` and see if the generated argocd application (/config/argcod/<env>-<app>-app,xml) spec/source/path uses "overlays" folder instead of "base".

2020-11-25 07:29 UTC, amitkrout commented
/ok-to-test

2020-11-25 15:49 UTC, wtam2018 reviewed
Please sync to the latest.   `makeSource` is now `makeAppSource` and you will need to fix `makeEnvSource` as well.

2020-11-25 15:52 UTC, bigkevmcd requested changes
This isn't yet complete, there are other points where overlays are being used in the ArgoCD configuration.

2020-11-26 17:28 UTC, iam-veeramalla commented
> Please sync to the latest. `makeSource` is now `makeAppSource` and you will need to fix `makeEnvSource` as well.

Made changes accordingly and modified unit tests to catch any future modifications.

2020-11-26 17:28 UTC, iam-veeramalla commented
> This isn't yet complete, there are other points where overlays are being used in the ArgoCD configuration.

@bigkevmcd made the required changes

2020-11-27 10:26 UTC, bigkevmcd commented
/retest

2020-11-27 12:48 UTC, bigkevmcd commented on pkg/pipelines/argocd/argocd_test.go
> +					Path:    filepath.Join(config.PathForApplication(testEnv, testApp), "overlays"),
I'd probably have simplified both of these to using the same pattern, but this works for me.

2020-11-27 12:48 UTC, bigkevmcd commented
/approve

2020-11-27 12:48 UTC, bigkevmcd commented
/lgtm

2020-11-27 13:00 UTC, merged